// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/strmangle"
)

// Smallblog is an object representing the database table.
type Smallblog struct {
	ID         int         `boil:"id" json:"id" toml:"id" yaml:"id"`
	ParentId   null.Int    `boil:"parentId" json:"parentId,omitempty" toml:"parentId" yaml:"parentId,omitempty"`
	Title      null.String `boil:"title" json:"title,omitempty" toml:"title" yaml:"title,omitempty"`
	Content    null.String `boil:"content" json:"content,omitempty" toml:"content" yaml:"content,omitempty"`
	CreateTime null.Time   `boil:"createTime" json:"createTime,omitempty" toml:"createTime" yaml:"createTime,omitempty"`
	CreateUser null.String `boil:"createUser" json:"createUser,omitempty" toml:"createUser" yaml:"createUser,omitempty"`
	UpdateTime null.Time   `boil:"updateTime" json:"updateTime,omitempty" toml:"updateTime" yaml:"updateTime,omitempty"`
	UpdateUser null.String `boil:"updateUser" json:"updateUser,omitempty" toml:"updateUser" yaml:"updateUser,omitempty"`

	R *smallblogR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L smallblogL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var SmallblogColumns = struct {
	ID         string
	ParentId   string
	Title      string
	Content    string
	CreateTime string
	CreateUser string
	UpdateTime string
	UpdateUser string
}{
	ID:         "id",
	ParentId:   "parentId",
	Title:      "title",
	Content:    "content",
	CreateTime: "createTime",
	CreateUser: "createUser",
	UpdateTime: "updateTime",
	UpdateUser: "updateUser",
}

// Generated where

type whereHelpernull_Int struct{ field string }

func (w whereHelpernull_Int) EQ(x null.Int) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Int) NEQ(x null.Int) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Int) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Int) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }
func (w whereHelpernull_Int) LT(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Int) LTE(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Int) GT(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Int) GTE(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

var SmallblogWhere = struct {
	ID         whereHelperint
	ParentId   whereHelpernull_Int
	Title      whereHelpernull_String
	Content    whereHelpernull_String
	CreateTime whereHelpernull_Time
	CreateUser whereHelpernull_String
	UpdateTime whereHelpernull_Time
	UpdateUser whereHelpernull_String
}{
	ID:         whereHelperint{field: "`smallblog`.`id`"},
	ParentId:   whereHelpernull_Int{field: "`smallblog`.`parentId`"},
	Title:      whereHelpernull_String{field: "`smallblog`.`title`"},
	Content:    whereHelpernull_String{field: "`smallblog`.`content`"},
	CreateTime: whereHelpernull_Time{field: "`smallblog`.`createTime`"},
	CreateUser: whereHelpernull_String{field: "`smallblog`.`createUser`"},
	UpdateTime: whereHelpernull_Time{field: "`smallblog`.`updateTime`"},
	UpdateUser: whereHelpernull_String{field: "`smallblog`.`updateUser`"},
}

// SmallblogRels is where relationship names are stored.
var SmallblogRels = struct {
}{}

// smallblogR is where relationships are stored.
type smallblogR struct {
}

// NewStruct creates a new relationship struct
func (*smallblogR) NewStruct() *smallblogR {
	return &smallblogR{}
}

// smallblogL is where Load methods for each relationship are stored.
type smallblogL struct{}

var (
	smallblogAllColumns            = []string{"id", "parentId", "title", "content", "createTime", "createUser", "updateTime", "updateUser"}
	smallblogColumnsWithoutDefault = []string{"id", "parentId", "title", "content", "createTime", "createUser", "updateTime", "updateUser"}
	smallblogColumnsWithDefault    = []string{}
	smallblogPrimaryKeyColumns     = []string{"id"}
)

type (
	// SmallblogSlice is an alias for a slice of pointers to Smallblog.
	// This should generally be used opposed to []Smallblog.
	SmallblogSlice []*Smallblog
	// SmallblogHook is the signature for custom Smallblog hook methods
	SmallblogHook func(context.Context, boil.ContextExecutor, *Smallblog) error

	smallblogQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	smallblogType                 = reflect.TypeOf(&Smallblog{})
	smallblogMapping              = queries.MakeStructMapping(smallblogType)
	smallblogPrimaryKeyMapping, _ = queries.BindMapping(smallblogType, smallblogMapping, smallblogPrimaryKeyColumns)
	smallblogInsertCacheMut       sync.RWMutex
	smallblogInsertCache          = make(map[string]insertCache)
	smallblogUpdateCacheMut       sync.RWMutex
	smallblogUpdateCache          = make(map[string]updateCache)
	smallblogUpsertCacheMut       sync.RWMutex
	smallblogUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var smallblogBeforeInsertHooks []SmallblogHook
var smallblogBeforeUpdateHooks []SmallblogHook
var smallblogBeforeDeleteHooks []SmallblogHook
var smallblogBeforeUpsertHooks []SmallblogHook

var smallblogAfterInsertHooks []SmallblogHook
var smallblogAfterSelectHooks []SmallblogHook
var smallblogAfterUpdateHooks []SmallblogHook
var smallblogAfterDeleteHooks []SmallblogHook
var smallblogAfterUpsertHooks []SmallblogHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Smallblog) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range smallblogBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Smallblog) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range smallblogBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Smallblog) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range smallblogBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Smallblog) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range smallblogBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Smallblog) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range smallblogAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Smallblog) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range smallblogAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Smallblog) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range smallblogAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Smallblog) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range smallblogAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Smallblog) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range smallblogAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddSmallblogHook registers your hook function for all future operations.
func AddSmallblogHook(hookPoint boil.HookPoint, smallblogHook SmallblogHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		smallblogBeforeInsertHooks = append(smallblogBeforeInsertHooks, smallblogHook)
	case boil.BeforeUpdateHook:
		smallblogBeforeUpdateHooks = append(smallblogBeforeUpdateHooks, smallblogHook)
	case boil.BeforeDeleteHook:
		smallblogBeforeDeleteHooks = append(smallblogBeforeDeleteHooks, smallblogHook)
	case boil.BeforeUpsertHook:
		smallblogBeforeUpsertHooks = append(smallblogBeforeUpsertHooks, smallblogHook)
	case boil.AfterInsertHook:
		smallblogAfterInsertHooks = append(smallblogAfterInsertHooks, smallblogHook)
	case boil.AfterSelectHook:
		smallblogAfterSelectHooks = append(smallblogAfterSelectHooks, smallblogHook)
	case boil.AfterUpdateHook:
		smallblogAfterUpdateHooks = append(smallblogAfterUpdateHooks, smallblogHook)
	case boil.AfterDeleteHook:
		smallblogAfterDeleteHooks = append(smallblogAfterDeleteHooks, smallblogHook)
	case boil.AfterUpsertHook:
		smallblogAfterUpsertHooks = append(smallblogAfterUpsertHooks, smallblogHook)
	}
}

// One returns a single smallblog record from the query.
func (q smallblogQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Smallblog, error) {
	o := &Smallblog{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for smallblog")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Smallblog records from the query.
func (q smallblogQuery) All(ctx context.Context, exec boil.ContextExecutor) (SmallblogSlice, error) {
	var o []*Smallblog

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Smallblog slice")
	}

	if len(smallblogAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Smallblog records in the query.
func (q smallblogQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count smallblog rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q smallblogQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if smallblog exists")
	}

	return count > 0, nil
}

// Smallblogs retrieves all the records using an executor.
func Smallblogs(mods ...qm.QueryMod) smallblogQuery {
	mods = append(mods, qm.From("`smallblog`"))
	return smallblogQuery{NewQuery(mods...)}
}

// FindSmallblog retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindSmallblog(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*Smallblog, error) {
	smallblogObj := &Smallblog{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `smallblog` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, smallblogObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from smallblog")
	}

	return smallblogObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Smallblog) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no smallblog provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(smallblogColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	smallblogInsertCacheMut.RLock()
	cache, cached := smallblogInsertCache[key]
	smallblogInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			smallblogAllColumns,
			smallblogColumnsWithDefault,
			smallblogColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(smallblogType, smallblogMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(smallblogType, smallblogMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `smallblog` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `smallblog` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `smallblog` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, smallblogPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into smallblog")
	}

	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for smallblog")
	}

CacheNoHooks:
	if !cached {
		smallblogInsertCacheMut.Lock()
		smallblogInsertCache[key] = cache
		smallblogInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Smallblog.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Smallblog) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	smallblogUpdateCacheMut.RLock()
	cache, cached := smallblogUpdateCache[key]
	smallblogUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			smallblogAllColumns,
			smallblogPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update smallblog, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `smallblog` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, smallblogPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(smallblogType, smallblogMapping, append(wl, smallblogPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update smallblog row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for smallblog")
	}

	if !cached {
		smallblogUpdateCacheMut.Lock()
		smallblogUpdateCache[key] = cache
		smallblogUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q smallblogQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for smallblog")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for smallblog")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o SmallblogSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), smallblogPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `smallblog` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, smallblogPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in smallblog slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all smallblog")
	}
	return rowsAff, nil
}

var mySQLSmallblogUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Smallblog) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no smallblog provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(smallblogColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLSmallblogUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	smallblogUpsertCacheMut.RLock()
	cache, cached := smallblogUpsertCache[key]
	smallblogUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			smallblogAllColumns,
			smallblogColumnsWithDefault,
			smallblogColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			smallblogAllColumns,
			smallblogPrimaryKeyColumns,
		)

		if len(update) == 0 {
			return errors.New("models: unable to upsert smallblog, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "smallblog", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `smallblog` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(smallblogType, smallblogMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(smallblogType, smallblogMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	_, err = exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for smallblog")
	}

	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(smallblogType, smallblogMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for smallblog")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for smallblog")
	}

CacheNoHooks:
	if !cached {
		smallblogUpsertCacheMut.Lock()
		smallblogUpsertCache[key] = cache
		smallblogUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Smallblog record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Smallblog) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Smallblog provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), smallblogPrimaryKeyMapping)
	sql := "DELETE FROM `smallblog` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from smallblog")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for smallblog")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q smallblogQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no smallblogQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from smallblog")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for smallblog")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o SmallblogSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(smallblogBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), smallblogPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `smallblog` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, smallblogPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from smallblog slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for smallblog")
	}

	if len(smallblogAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Smallblog) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindSmallblog(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *SmallblogSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := SmallblogSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), smallblogPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `smallblog`.* FROM `smallblog` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, smallblogPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in SmallblogSlice")
	}

	*o = slice

	return nil
}

// SmallblogExists checks if the Smallblog row exists.
func SmallblogExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `smallblog` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if smallblog exists")
	}

	return exists, nil
}
